### ISSUE TITLE
xfwm4 and xfce4-panel

### ISSUE THREAD

**Issue by denikris** [Vistaus/Blue-Face#5]
![xfce4-panel blueface](https://user-images.githubusercontent.com/16707606/32414912-f0a91056-c262-11e7-872c-540952862298.png)
the panel should be dark, right?

![xfwm4 blueface](https://user-images.githubusercontent.com/16707606/32414913-f10020ee-c262-11e7-8862-c7bbd50211e5.png)
'close' button invisible, two window component look not match the color, and when window maximized, 'restore' button become black, and there is a weird dots above the window and window corner not smooth, maybe make it square will be good

:-)

**Comment by Vistaus** [comment]
I dunno. I don't use Xfce, so I can't help you with that, sorry.
